name: ich-tanke-strom_CPO_Monitoring
channels:
  - conda-forge
dependencies:
  - requests==2.29.0
  - pandas==2.0.1
  - geopandas==0.12.2
  - fiona==1.9.3
  - leafmap==0.20.0
  - numpy==1.24.2
  - matplotlib==3.7.0
  - notebook==6.5.4
